### ISSUE TITLE
Add ordering of jQuery and BS js to FAQ

### ISSUE THREAD

**Issue by ewels** [ewels/cpt-bootstrap-carousel#26]
Add a section to the FAQ about carousels not sliding, mentioning that the order of jQuery and BS imports is important.

See http://wordpress.org/support/topic/css-andor-javascript-not-loading-properly

**Comment by kevinvess** [comment]
You need to properly [enqueue your scripts](https://developer.wordpress.org/themes/basics/including-css-javascript/) so they are loaded after _wherever_ jQuery gets loaded.

Additionally, you shouldn't ask people to just add the jQuery script after the `wp_head()` function in their theme's `header.php` file – that is bad practice and will cause conflicts with other plugins/themes which are also loading jQuery.

**Comment by ewels** [comment]
Thanks for the tips @kevinvess. You may notice that this issue is nearly three and a half years old. I don't actively use or develop this WordPress plugin any more, but you're welcome to submit a pull-request with changes and I'll try to get to doing a maintenance release some time in the future.

Phil

**Comment by kevinvess** [comment]
Thanks for the quick response!

I realized the issue was old, but figured I'd comment here instead of opening a new issue since it's directly related. I didn't realize you were no longer supporting the plugin, maybe you should update the readme and WordPress.org to reflect that?

A project I'm working on is using your plugin and it was throwing an error because the embedded `<script>` came before the jQuery library being loaded in the footer.

If I have time, I'll submit a pull-request; but for now my bandaid of setting a theme script that depends on jQuery to load in the head works for now (because it moved the jQuery script from the footer to the head and above your embedded script).

**Comment by ewels** [comment]
Ok, a PR would be much appreciated, thanks.

I probably meant developing rather than supporting - I'm happy to push releases for major bugs but I haven't touched the code myself for a long time now. Having not done any WordPress dev for ages means that it takes me a long time to get a test environment back up and running and to remember how to write PHP :)

Phil
