### ISSUE TITLE
Add multiple images at once to a category

### ISSUE THREAD

**Issue by bonnsbonn** [ewels/cpt-bootstrap-carousel#70]
Would it be possible to mass add images to a particular category.  I love the WP plugin but am challenged with having multiple sliders to create with multiple images per each slider.  I really appreciate your hard work and will be buying ye a beer :)

**Comment by ewels** [comment]
Hi @bonnsbonn,

I'm a little confused - you can already do this, can't you?

> * `category` _(default all)_
>	* Filter carousel items by a comma separated list of carousel category slugs.
>	* `[image-carousel category="homepage,highlights"]`

Or is this not what you mean?

Phil

**Comment by bonnsbonn** [comment]
no I mean as when I create category and then have to manually add each image to an assigned category one by one.. unless there is something I missed.. say I have 1 carousel I need to create and I have 6 images I need to add from the media gallery.. I have to select one by one and assign each to their own custom post as the featured image.. at least that is how I have been doing it

**Comment by ewels** [comment]
Ah I see, sorry - I don't think that there's currently an easy way to add multiple images from the media gallery I'm afraid, but it is possible to batch-change their categories once added:

1. Go to the Carousel admin page
2. Select the check boxes for the images that you'd like to add to a category
3. Select 'Edit' from the 'Bulk Options' dropdown box
4. Tick relevant category boxes in the categories section of the box that should appear and hit save.

Does that do what you want? The bulk creation of carousel items from the media library is a nice idea, but I'm afraid I can't promise to add that feature any time soon (though I will create an issue for it so that I don't forget).

Phil

**Comment by bonnsbonn** [comment]
Hi Yes I figured out how to do the batch change.. its the batch add part that I am after..  If you saw how many images I am dealing with and categories you would appreciate why I am hoping this would be a nice feature request :) trust me it is akin to watching paint dry..  I do appreciate your plugin very much .. it has been a great asset on another site I have built and was really wanting to use it on another site I am on.. I will keep tabs and watch for updates.. sadly I am not a php coder so I would be of no help in that venue..  Please enjoy the beer I tried to estimate how much one would cost over there.  Thank you so much for your time and attention to this issue and please have an awesome day/evening!

**Comment by ewels** [comment]
Ok, sorry not to be more help and thanks for the donation! I will raise a cold one to you tonight :)
