### ISSUE TITLE
Override template in my theme

### ISSUE THREAD

**Issue by kpaulsson** [ewels/cpt-bootstrap-carousel#74]
Hi I tried to override the plugin template in the theme that I am doing for my employers homepage. I need to add some classes and som markup in the carousel. Is there a feature so that I can  just copy a template to my theme and edit in there?

Like company-theme/plugins/cpt-bootstrap-carousel/cptbc-frontend.php

**Comment by ewels** [comment]
Hi @kpaulsson,

I'm afraid not - your best bet is probably to fork this repository and edit the files, making your own version of the plugin.

Obviously it depends what you're trying to achieve, but most people's support requests are usually achievable by using the CSS classes that are already there. So that's another option.

Phil

**Comment by kpaulsson** [comment]
I copied cptbc-frontend.php to themes/mytheme/inc/, changed the name of the functions a little bit. Changed the name of the shortcode, included the file in my functions.php and adapted the code I needed it. Works great.

**Comment by ewels** [comment]
Great! Glad you sorted it.
